import { useQuery } from '@tanstack/react-query'

export type SearchEntityType = 'player' | 'team' | 'league'

export interface SearchEntity {
  t: SearchEntityType
  id: number
  n: string
  logo?: string
  r?: string
  tier?: string
  /** League tier id: 1 PREMIUM · 2 PROFESSIONAL · 3 SEMI_PRO (4 AMATEUR is excluded). */
  ti?: number
  /** Popularity tie-breaker (per-type): player games, team Elo, league match count. */
  w?: number
}

interface SearchIndex {
  generated: string
  entities: SearchEntity[]
}

// Generated by scripts/build-sitemap.cjs into both public/ (served by vite dev)
// and dist/ (deployed). On any failure we degrade to an empty entity list —
// static-page search still works.
const INDEX_URL = '/search-index.json'

export function useSearchIndex(enabled: boolean) {
  return useQuery<SearchEntity[]>({
    queryKey: ['search-index'],
    queryFn: async () => {
      const res = await fetch(INDEX_URL, { headers: { Accept: 'application/json' } })
      if (!res.ok) throw new Error(`search-index ${res.status}`)
      const ct = res.headers.get('content-type') ?? ''
      if (!ct.includes('json')) throw new Error('search-index not deployed (got non-JSON)')
      const data: SearchIndex = await res.json()
      return data.entities ?? []
    },
    enabled,
    staleTime: 60 * 60 * 1000,
    gcTime: 24 * 60 * 60 * 1000,
    retry: 1,
  })
}
