// Auto-generated by scripts/update-static-data.cjs
// Last updated: 2026-03-14T23:40:53.407Z

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const buildings: any = {
  "types": {
    "RAX": "Barracks",
    "TOWER": "Tower",
    "SHRINE": "Shrine"
  },
  "lanes": {
    "MIDDLE": "Middle",
    "BOTTOM": "Bottom",
    "TOP": "Top",
    "OTHER": "Other"
  },
  "tiers": {
    "1": "1",
    "2": "2",
    "3": "3",
    "4": "4",
    "-1": "Other"
  }
}
