// Auto-generated by scripts/update-static-data.cjs
// Last updated: 2026-03-14T23:40:52.973Z

export interface HeroData {
  name: string
  picture: string
}

/** Map of hero ID to hero data */
export const heroesById: Record<string, HeroData> = {
  "1": {
    "name": "Anti-Mage",
    "picture": "antimage"
  },
  "2": {
    "name": "Axe",
    "picture": "axe"
  },
  "3": {
    "name": "Bane",
    "picture": "bane"
  },
  "4": {
    "name": "Bloodseeker",
    "picture": "bloodseeker"
  },
  "5": {
    "name": "Crystal Maiden",
    "picture": "crystal_maiden"
  },
  "6": {
    "name": "Drow Ranger",
    "picture": "drow_ranger"
  },
  "7": {
    "name": "Earthshaker",
    "picture": "earthshaker"
  },
  "8": {
    "name": "Juggernaut",
    "picture": "juggernaut"
  },
  "9": {
    "name": "Mirana",
    "picture": "mirana"
  },
  "10": {
    "name": "Morphling",
    "picture": "morphling"
  },
  "11": {
    "name": "Shadow Fiend",
    "picture": "nevermore"
  },
  "12": {
    "name": "Phantom Lancer",
    "picture": "phantom_lancer"
  },
  "13": {
    "name": "Puck",
    "picture": "puck"
  },
  "14": {
    "name": "Pudge",
    "picture": "pudge"
  },
  "15": {
    "name": "Razor",
    "picture": "razor"
  },
  "16": {
    "name": "Sand King",
    "picture": "sand_king"
  },
  "17": {
    "name": "Storm Spirit",
    "picture": "storm_spirit"
  },
  "18": {
    "name": "Sven",
    "picture": "sven"
  },
  "19": {
    "name": "Tiny",
    "picture": "tiny"
  },
  "20": {
    "name": "Vengeful Spirit",
    "picture": "vengefulspirit"
  },
  "21": {
    "name": "Windranger",
    "picture": "windrunner"
  },
  "22": {
    "name": "Zeus",
    "picture": "zuus"
  },
  "23": {
    "name": "Kunkka",
    "picture": "kunkka"
  },
  "25": {
    "name": "Lina",
    "picture": "lina"
  },
  "26": {
    "name": "Lion",
    "picture": "lion"
  },
  "27": {
    "name": "Shadow Shaman",
    "picture": "shadow_shaman"
  },
  "28": {
    "name": "Slardar",
    "picture": "slardar"
  },
  "29": {
    "name": "Tidehunter",
    "picture": "tidehunter"
  },
  "30": {
    "name": "Witch Doctor",
    "picture": "witch_doctor"
  },
  "31": {
    "name": "Lich",
    "picture": "lich"
  },
  "32": {
    "name": "Riki",
    "picture": "riki"
  },
  "33": {
    "name": "Enigma",
    "picture": "enigma"
  },
  "34": {
    "name": "Tinker",
    "picture": "tinker"
  },
  "35": {
    "name": "Sniper",
    "picture": "sniper"
  },
  "36": {
    "name": "Necrophos",
    "picture": "necrolyte"
  },
  "37": {
    "name": "Warlock",
    "picture": "warlock"
  },
  "38": {
    "name": "Beastmaster",
    "picture": "beastmaster"
  },
  "39": {
    "name": "Queen of Pain",
    "picture": "queenofpain"
  },
  "40": {
    "name": "Venomancer",
    "picture": "venomancer"
  },
  "41": {
    "name": "Faceless Void",
    "picture": "faceless_void"
  },
  "42": {
    "name": "Wraith King",
    "picture": "skeleton_king"
  },
  "43": {
    "name": "Death Prophet",
    "picture": "death_prophet"
  },
  "44": {
    "name": "Phantom Assassin",
    "picture": "phantom_assassin"
  },
  "45": {
    "name": "Pugna",
    "picture": "pugna"
  },
  "46": {
    "name": "Templar Assassin",
    "picture": "templar_assassin"
  },
  "47": {
    "name": "Viper",
    "picture": "viper"
  },
  "48": {
    "name": "Luna",
    "picture": "luna"
  },
  "49": {
    "name": "Dragon Knight",
    "picture": "dragon_knight"
  },
  "50": {
    "name": "Dazzle",
    "picture": "dazzle"
  },
  "51": {
    "name": "Clockwerk",
    "picture": "rattletrap"
  },
  "52": {
    "name": "Leshrac",
    "picture": "leshrac"
  },
  "53": {
    "name": "Nature's Prophet",
    "picture": "furion"
  },
  "54": {
    "name": "Lifestealer",
    "picture": "life_stealer"
  },
  "55": {
    "name": "Dark Seer",
    "picture": "dark_seer"
  },
  "56": {
    "name": "Clinkz",
    "picture": "clinkz"
  },
  "57": {
    "name": "Omniknight",
    "picture": "omniknight"
  },
  "58": {
    "name": "Enchantress",
    "picture": "enchantress"
  },
  "59": {
    "name": "Huskar",
    "picture": "huskar"
  },
  "60": {
    "name": "Night Stalker",
    "picture": "night_stalker"
  },
  "61": {
    "name": "Broodmother",
    "picture": "broodmother"
  },
  "62": {
    "name": "Bounty Hunter",
    "picture": "bounty_hunter"
  },
  "63": {
    "name": "Weaver",
    "picture": "weaver"
  },
  "64": {
    "name": "Jakiro",
    "picture": "jakiro"
  },
  "65": {
    "name": "Batrider",
    "picture": "batrider"
  },
  "66": {
    "name": "Chen",
    "picture": "chen"
  },
  "67": {
    "name": "Spectre",
    "picture": "spectre"
  },
  "68": {
    "name": "Ancient Apparition",
    "picture": "ancient_apparition"
  },
  "69": {
    "name": "Doom",
    "picture": "doom_bringer"
  },
  "70": {
    "name": "Ursa",
    "picture": "ursa"
  },
  "71": {
    "name": "Spirit Breaker",
    "picture": "spirit_breaker"
  },
  "72": {
    "name": "Gyrocopter",
    "picture": "gyrocopter"
  },
  "73": {
    "name": "Alchemist",
    "picture": "alchemist"
  },
  "74": {
    "name": "Invoker",
    "picture": "invoker"
  },
  "75": {
    "name": "Silencer",
    "picture": "silencer"
  },
  "76": {
    "name": "Outworld Devourer",
    "picture": "obsidian_destroyer"
  },
  "77": {
    "name": "Lycan",
    "picture": "lycan"
  },
  "78": {
    "name": "Brewmaster",
    "picture": "brewmaster"
  },
  "79": {
    "name": "Shadow Demon",
    "picture": "shadow_demon"
  },
  "80": {
    "name": "Lone Druid",
    "picture": "lone_druid"
  },
  "81": {
    "name": "Chaos Knight",
    "picture": "chaos_knight"
  },
  "82": {
    "name": "Meepo",
    "picture": "meepo"
  },
  "83": {
    "name": "Treant Protector",
    "picture": "treant"
  },
  "84": {
    "name": "Ogre Magi",
    "picture": "ogre_magi"
  },
  "85": {
    "name": "Undying",
    "picture": "undying"
  },
  "86": {
    "name": "Rubick",
    "picture": "rubick"
  },
  "87": {
    "name": "Disruptor",
    "picture": "disruptor"
  },
  "88": {
    "name": "Nyx Assassin",
    "picture": "nyx_assassin"
  },
  "89": {
    "name": "Naga Siren",
    "picture": "naga_siren"
  },
  "90": {
    "name": "Keeper of the Light",
    "picture": "keeper_of_the_light"
  },
  "91": {
    "name": "Io",
    "picture": "wisp"
  },
  "92": {
    "name": "Visage",
    "picture": "visage"
  },
  "93": {
    "name": "Slark",
    "picture": "slark"
  },
  "94": {
    "name": "Medusa",
    "picture": "medusa"
  },
  "95": {
    "name": "Troll Warlord",
    "picture": "troll_warlord"
  },
  "96": {
    "name": "Centaur Warrunner",
    "picture": "centaur"
  },
  "97": {
    "name": "Magnus",
    "picture": "magnataur"
  },
  "98": {
    "name": "Timbersaw",
    "picture": "shredder"
  },
  "99": {
    "name": "Bristleback",
    "picture": "bristleback"
  },
  "100": {
    "name": "Tusk",
    "picture": "tusk"
  },
  "101": {
    "name": "Skywrath Mage",
    "picture": "skywrath_mage"
  },
  "102": {
    "name": "Abaddon",
    "picture": "abaddon"
  },
  "103": {
    "name": "Elder Titan",
    "picture": "elder_titan"
  },
  "104": {
    "name": "Legion Commander",
    "picture": "legion_commander"
  },
  "105": {
    "name": "Techies",
    "picture": "techies"
  },
  "106": {
    "name": "Ember Spirit",
    "picture": "ember_spirit"
  },
  "107": {
    "name": "Earth Spirit",
    "picture": "earth_spirit"
  },
  "108": {
    "name": "Underlord",
    "picture": "abyssal_underlord"
  },
  "109": {
    "name": "Terrorblade",
    "picture": "terrorblade"
  },
  "110": {
    "name": "Phoenix",
    "picture": "phoenix"
  },
  "111": {
    "name": "Oracle",
    "picture": "oracle"
  },
  "112": {
    "name": "Winter Wyvern",
    "picture": "winter_wyvern"
  },
  "113": {
    "name": "Arc Warden",
    "picture": "arc_warden"
  },
  "114": {
    "name": "Monkey King",
    "picture": "monkey_king"
  },
  "119": {
    "name": "Dark Willow",
    "picture": "dark_willow"
  },
  "120": {
    "name": "Pangolier",
    "picture": "pangolier"
  },
  "121": {
    "name": "Grimstroke",
    "picture": "grimstroke"
  },
  "123": {
    "name": "Hoodwink",
    "picture": "hoodwink"
  },
  "126": {
    "name": "Void Spirit",
    "picture": "void_spirit"
  },
  "128": {
    "name": "Snapfire",
    "picture": "snapfire"
  },
  "129": {
    "name": "Mars",
    "picture": "mars"
  },
  "131": {
    "name": "Ringmaster",
    "picture": "ringmaster"
  },
  "135": {
    "name": "Dawnbreaker",
    "picture": "dawnbreaker"
  },
  "136": {
    "name": "Marci",
    "picture": "marci"
  },
  "137": {
    "name": "Primal Beast",
    "picture": "primal_beast"
  },
  "138": {
    "name": "Muerta",
    "picture": "muerta"
  },
  "145": {
    "name": "Kez",
    "picture": "kez"
  },
  "155": {
    "name": "Largo",
    "picture": "largo"
  }
}

/** Get hero by numeric ID */
export function getHeroById(id: number | string): HeroData | undefined {
  return heroesById[String(id)]
}

/** Total number of heroes */
export const HERO_COUNT = 127
