// Auto-generated by scripts/update-static-data.cjs
// Last updated: 2026-03-16T23:29:53.603Z

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const items: any = {
  "1": {
    "shortName": "item_blink",
    "longName": "Blink Dagger",
    "cost": null
  },
  "2": {
    "shortName": "item_blades_of_attack",
    "longName": "Blades of Attack",
    "cost": null
  },
  "3": {
    "shortName": "item_broadsword",
    "longName": "Broadsword",
    "cost": null
  },
  "4": {
    "shortName": "item_chainmail",
    "longName": "Chainmail",
    "cost": null
  },
  "5": {
    "shortName": "item_claymore",
    "longName": "Claymore",
    "cost": null
  },
  "6": {
    "shortName": "item_helm_of_iron_will",
    "longName": "Helm of Iron Will",
    "cost": null
  },
  "7": {
    "shortName": "item_javelin",
    "longName": "Javelin",
    "cost": null
  },
  "8": {
    "shortName": "item_mithril_hammer",
    "longName": "Mithril Hammer",
    "cost": null
  },
  "9": {
    "shortName": "item_platemail",
    "longName": "Platemail",
    "cost": null
  },
  "10": {
    "shortName": "item_quarterstaff",
    "longName": "Quarterstaff",
    "cost": null
  },
  "11": {
    "shortName": "item_quelling_blade",
    "longName": "Quelling Blade",
    "cost": null
  },
  "12": {
    "shortName": "item_ring_of_protection",
    "longName": "Ring of Protection",
    "cost": null
  },
  "13": {
    "shortName": "item_gauntlets",
    "longName": "Gauntlets of Strength",
    "cost": null
  },
  "14": {
    "shortName": "item_slippers",
    "longName": "Slippers of Agility",
    "cost": null
  },
  "15": {
    "shortName": "item_mantle",
    "longName": "Mantle of Intelligence",
    "cost": null
  },
  "16": {
    "shortName": "item_branches",
    "longName": "Iron Branch",
    "cost": null
  },
  "17": {
    "shortName": "item_belt_of_strength",
    "longName": "Belt of Strength",
    "cost": null
  },
  "18": {
    "shortName": "item_boots_of_elves",
    "longName": "Band of Elvenskin",
    "cost": null
  },
  "19": {
    "shortName": "item_robe",
    "longName": "Robe of the Magi",
    "cost": null
  },
  "20": {
    "shortName": "item_circlet",
    "longName": "Circlet",
    "cost": null
  },
  "21": {
    "shortName": "item_ogre_axe",
    "longName": "Ogre Axe",
    "cost": null
  },
  "22": {
    "shortName": "item_blade_of_alacrity",
    "longName": "Blade of Alacrity",
    "cost": null
  },
  "23": {
    "shortName": "item_staff_of_wizardry",
    "longName": "Staff of Wizardry",
    "cost": null
  },
  "24": {
    "shortName": "item_ultimate_orb",
    "longName": "Ultimate Orb",
    "cost": null
  },
  "25": {
    "shortName": "item_gloves",
    "longName": "Gloves of Haste",
    "cost": null
  },
  "26": {
    "shortName": "item_lifesteal",
    "longName": "Morbid Mask",
    "cost": null
  },
  "27": {
    "shortName": "item_ring_of_regen",
    "longName": "Ring of Regen",
    "cost": null
  },
  "28": {
    "shortName": "item_sobi_mask",
    "longName": "Sage's Mask",
    "cost": null
  },
  "29": {
    "shortName": "item_boots",
    "longName": "Boots of Speed",
    "cost": null
  },
  "30": {
    "shortName": "item_gem",
    "longName": "Gem of True Sight",
    "cost": null
  },
  "31": {
    "shortName": "item_cloak",
    "longName": "Cloak",
    "cost": null
  },
  "32": {
    "shortName": "item_talisman_of_evasion",
    "longName": "Talisman of Evasion",
    "cost": null
  },
  "33": {
    "shortName": "item_cheese",
    "longName": "Cheese",
    "cost": null
  },
  "34": {
    "shortName": "item_magic_stick",
    "longName": "Magic Stick",
    "cost": null
  },
  "35": {
    "shortName": "item_recipe_magic_wand",
    "longName": "Magic Wand Recipe",
    "cost": null
  },
  "36": {
    "shortName": "item_magic_wand",
    "longName": "Magic Wand",
    "cost": null
  },
  "37": {
    "shortName": "item_ghost",
    "longName": "Ghost Scepter",
    "cost": null
  },
  "38": {
    "shortName": "item_clarity",
    "longName": "Clarity",
    "cost": null
  },
  "39": {
    "shortName": "item_flask",
    "longName": "Healing Salve",
    "cost": null
  },
  "40": {
    "shortName": "item_dust",
    "longName": "Dust of Appearance",
    "cost": null
  },
  "41": {
    "shortName": "item_bottle",
    "longName": "Bottle",
    "cost": null
  },
  "42": {
    "shortName": "item_ward_observer",
    "longName": "Observer Ward",
    "cost": null
  },
  "43": {
    "shortName": "item_ward_sentry",
    "longName": "Sentry Ward",
    "cost": null
  },
  "44": {
    "shortName": "item_tango",
    "longName": "Tango",
    "cost": null
  },
  "45": {
    "shortName": "item_courier",
    "longName": "Animal Courier",
    "cost": null
  },
  "46": {
    "shortName": "item_tpscroll",
    "longName": "Town Portal Scroll",
    "cost": null
  },
  "47": {
    "shortName": "item_recipe_travel_boots",
    "longName": "Boots of Travel Recipe",
    "cost": null
  },
  "48": {
    "shortName": "item_travel_boots",
    "longName": "Boots of Travel",
    "cost": null
  },
  "49": {
    "shortName": "item_recipe_phase_boots",
    "longName": "",
    "cost": null
  },
  "50": {
    "shortName": "item_phase_boots",
    "longName": "Phase Boots",
    "cost": null
  },
  "51": {
    "shortName": "item_demon_edge",
    "longName": "Demon Edge",
    "cost": null
  },
  "52": {
    "shortName": "item_eagle",
    "longName": "Eaglesong",
    "cost": null
  },
  "53": {
    "shortName": "item_reaver",
    "longName": "Reaver",
    "cost": null
  },
  "54": {
    "shortName": "item_relic",
    "longName": "Sacred Relic",
    "cost": null
  },
  "55": {
    "shortName": "item_hyperstone",
    "longName": "Hyperstone",
    "cost": null
  },
  "56": {
    "shortName": "item_ring_of_health",
    "longName": "Ring of Health",
    "cost": null
  },
  "57": {
    "shortName": "item_void_stone",
    "longName": "Void Stone",
    "cost": null
  },
  "58": {
    "shortName": "item_mystic_staff",
    "longName": "Mystic Staff",
    "cost": null
  },
  "59": {
    "shortName": "item_energy_booster",
    "longName": "Energy Booster",
    "cost": null
  },
  "60": {
    "shortName": "item_point_booster",
    "longName": "Point Booster",
    "cost": null
  },
  "61": {
    "shortName": "item_vitality_booster",
    "longName": "Vitality Booster",
    "cost": null
  },
  "62": {
    "shortName": "item_recipe_power_treads",
    "longName": "",
    "cost": null
  },
  "63": {
    "shortName": "item_power_treads",
    "longName": "Power Treads",
    "cost": null
  },
  "64": {
    "shortName": "item_recipe_hand_of_midas",
    "longName": "Hand of Midas Recipe",
    "cost": null
  },
  "65": {
    "shortName": "item_hand_of_midas",
    "longName": "Hand of Midas",
    "cost": null
  },
  "66": {
    "shortName": "item_recipe_oblivion_staff",
    "longName": "",
    "cost": null
  },
  "67": {
    "shortName": "item_oblivion_staff",
    "longName": "Oblivion Staff",
    "cost": null
  },
  "68": {
    "shortName": "item_recipe_pers",
    "longName": "",
    "cost": null
  },
  "69": {
    "shortName": "item_pers",
    "longName": "Perseverance",
    "cost": null
  },
  "70": {
    "shortName": "item_recipe_poor_mans_shield",
    "longName": "",
    "cost": null
  },
  "71": {
    "shortName": "item_poor_mans_shield",
    "longName": "Poor Man's Shield",
    "cost": null
  },
  "72": {
    "shortName": "item_recipe_bracer",
    "longName": "Bracer Recipe",
    "cost": null
  },
  "73": {
    "shortName": "item_bracer",
    "longName": "Bracer",
    "cost": null
  },
  "74": {
    "shortName": "item_recipe_wraith_band",
    "longName": "Wraith Band Recipe",
    "cost": null
  },
  "75": {
    "shortName": "item_wraith_band",
    "longName": "Wraith Band",
    "cost": null
  },
  "76": {
    "shortName": "item_recipe_null_talisman",
    "longName": "Null Talisman Recipe",
    "cost": null
  },
  "77": {
    "shortName": "item_null_talisman",
    "longName": "Null Talisman",
    "cost": null
  },
  "78": {
    "shortName": "item_recipe_mekansm",
    "longName": "Mekansm Recipe",
    "cost": null
  },
  "79": {
    "shortName": "item_mekansm",
    "longName": "Mekansm",
    "cost": null
  },
  "80": {
    "shortName": "item_recipe_vladmir",
    "longName": "Vladmir's Offering Recipe",
    "cost": null
  },
  "81": {
    "shortName": "item_vladmir",
    "longName": "Vladmir's Offering",
    "cost": null
  },
  "84": {
    "shortName": "item_flying_courier",
    "longName": "Flying Courier",
    "cost": 150
  },
  "85": {
    "shortName": "item_recipe_buckler",
    "longName": "Buckler Recipe",
    "cost": null
  },
  "86": {
    "shortName": "item_buckler",
    "longName": "Buckler",
    "cost": null
  },
  "87": {
    "shortName": "item_recipe_ring_of_basilius",
    "longName": "Ring of Basilius Recipe",
    "cost": null
  },
  "88": {
    "shortName": "item_ring_of_basilius",
    "longName": "Ring of Basilius",
    "cost": null
  },
  "89": {
    "shortName": "item_recipe_pipe",
    "longName": "Pipe of Insight Recipe",
    "cost": null
  },
  "90": {
    "shortName": "item_pipe",
    "longName": "Pipe of Insight",
    "cost": null
  },
  "91": {
    "shortName": "item_recipe_urn_of_shadows",
    "longName": "Urn of Shadows Recipe",
    "cost": null
  },
  "92": {
    "shortName": "item_urn_of_shadows",
    "longName": "Urn of Shadows",
    "cost": null
  },
  "93": {
    "shortName": "item_recipe_headdress",
    "longName": "Headdress Recipe",
    "cost": null
  },
  "94": {
    "shortName": "item_headdress",
    "longName": "Headdress",
    "cost": null
  },
  "95": {
    "shortName": "item_recipe_sheepstick",
    "longName": "Scythe of Vyse Recipe",
    "cost": null
  },
  "96": {
    "shortName": "item_sheepstick",
    "longName": "Scythe of Vyse",
    "cost": null
  },
  "97": {
    "shortName": "item_recipe_orchid",
    "longName": "Orchid Malevolence Recipe",
    "cost": null
  },
  "98": {
    "shortName": "item_orchid",
    "longName": "Orchid Malevolence",
    "cost": null
  },
  "99": {
    "shortName": "item_recipe_cyclone",
    "longName": "Eul's Scepter Recipe",
    "cost": null
  },
  "100": {
    "shortName": "item_cyclone",
    "longName": "Eul's Scepter of Divinity",
    "cost": null
  },
  "101": {
    "shortName": "item_recipe_force_staff",
    "longName": "Force Staff Recipe",
    "cost": null
  },
  "102": {
    "shortName": "item_force_staff",
    "longName": "Force Staff",
    "cost": null
  },
  "103": {
    "shortName": "item_recipe_dagon",
    "longName": "Dagon Recipe",
    "cost": null
  },
  "104": {
    "shortName": "item_dagon",
    "longName": "Dagon",
    "cost": null
  },
  "105": {
    "shortName": "item_recipe_necronomicon",
    "longName": "Necronomicon Recipe",
    "cost": null
  },
  "106": {
    "shortName": "item_necronomicon",
    "longName": "Necronomicon 1",
    "cost": null
  },
  "107": {
    "shortName": "item_recipe_ultimate_scepter",
    "longName": "",
    "cost": null
  },
  "108": {
    "shortName": "item_ultimate_scepter",
    "longName": "Aghanim's Scepter",
    "cost": null
  },
  "109": {
    "shortName": "item_recipe_refresher",
    "longName": "Refresher Orb Recipe",
    "cost": null
  },
  "110": {
    "shortName": "item_refresher",
    "longName": "Refresher Orb",
    "cost": null
  },
  "111": {
    "shortName": "item_recipe_assault",
    "longName": "Assault Cuirass Recipe",
    "cost": null
  },
  "112": {
    "shortName": "item_assault",
    "longName": "Assault Cuirass",
    "cost": null
  },
  "113": {
    "shortName": "item_recipe_heart",
    "longName": "Heart of Tarrasque Recipe",
    "cost": null
  },
  "114": {
    "shortName": "item_heart",
    "longName": "Heart of Tarrasque",
    "cost": null
  },
  "115": {
    "shortName": "item_recipe_black_king_bar",
    "longName": "Black King Bar Recipe",
    "cost": null
  },
  "116": {
    "shortName": "item_black_king_bar",
    "longName": "Black King Bar",
    "cost": null
  },
  "117": {
    "shortName": "item_aegis",
    "longName": "Aegis of the Immortal",
    "cost": null
  },
  "118": {
    "shortName": "item_recipe_shivas_guard",
    "longName": "Shiva's Guard Recipe",
    "cost": null
  },
  "119": {
    "shortName": "item_shivas_guard",
    "longName": "Shiva's Guard",
    "cost": null
  },
  "120": {
    "shortName": "item_recipe_bloodstone",
    "longName": "Bloodstone Recipe",
    "cost": null
  },
  "121": {
    "shortName": "item_bloodstone",
    "longName": "Bloodstone",
    "cost": null
  },
  "122": {
    "shortName": "item_recipe_sphere",
    "longName": "Linken's Sphere Recipe",
    "cost": null
  },
  "123": {
    "shortName": "item_sphere",
    "longName": "Linken's Sphere",
    "cost": null
  },
  "124": {
    "shortName": "item_recipe_vanguard",
    "longName": "",
    "cost": null
  },
  "125": {
    "shortName": "item_vanguard",
    "longName": "Vanguard",
    "cost": null
  },
  "126": {
    "shortName": "item_recipe_blade_mail",
    "longName": "Blade Mail Recipe",
    "cost": null
  },
  "127": {
    "shortName": "item_blade_mail",
    "longName": "Blade Mail",
    "cost": null
  },
  "128": {
    "shortName": "item_recipe_soul_booster",
    "longName": "",
    "cost": null
  },
  "129": {
    "shortName": "item_soul_booster",
    "longName": "Soul Booster",
    "cost": null
  },
  "130": {
    "shortName": "item_recipe_hood_of_defiance",
    "longName": "",
    "cost": null
  },
  "131": {
    "shortName": "item_hood_of_defiance",
    "longName": "Hood of Defiance",
    "cost": null
  },
  "132": {
    "shortName": "item_recipe_rapier",
    "longName": "Divine Rapier Recipe",
    "cost": null
  },
  "133": {
    "shortName": "item_rapier",
    "longName": "Divine Rapier",
    "cost": null
  },
  "134": {
    "shortName": "item_recipe_monkey_king_bar",
    "longName": "Monkey King Bar Recipe",
    "cost": null
  },
  "135": {
    "shortName": "item_monkey_king_bar",
    "longName": "Monkey King Bar",
    "cost": null
  },
  "136": {
    "shortName": "item_recipe_radiance",
    "longName": "Radiance Recipe",
    "cost": null
  },
  "137": {
    "shortName": "item_radiance",
    "longName": "Radiance",
    "cost": null
  },
  "138": {
    "shortName": "item_recipe_butterfly",
    "longName": "",
    "cost": null
  },
  "139": {
    "shortName": "item_butterfly",
    "longName": "Butterfly",
    "cost": null
  },
  "140": {
    "shortName": "item_recipe_greater_crit",
    "longName": "Daedalus Recipe",
    "cost": null
  },
  "141": {
    "shortName": "item_greater_crit",
    "longName": "Daedalus",
    "cost": null
  },
  "142": {
    "shortName": "item_recipe_basher",
    "longName": "Skull Basher Recipe",
    "cost": null
  },
  "143": {
    "shortName": "item_basher",
    "longName": "Skull Basher",
    "cost": null
  },
  "144": {
    "shortName": "item_recipe_bfury",
    "longName": "Battle Fury Recipe",
    "cost": null
  },
  "145": {
    "shortName": "item_bfury",
    "longName": "Battle Fury",
    "cost": null
  },
  "146": {
    "shortName": "item_recipe_manta",
    "longName": "Manta Style Recipe",
    "cost": null
  },
  "147": {
    "shortName": "item_manta",
    "longName": "Manta Style",
    "cost": null
  },
  "148": {
    "shortName": "item_recipe_lesser_crit",
    "longName": "Crystalys Recipe",
    "cost": null
  },
  "149": {
    "shortName": "item_lesser_crit",
    "longName": "Crystalys",
    "cost": null
  },
  "150": {
    "shortName": "item_recipe_armlet",
    "longName": "Armlet of Mordiggian Recipe",
    "cost": null
  },
  "151": {
    "shortName": "item_armlet",
    "longName": "Armlet of Mordiggian",
    "cost": null
  },
  "152": {
    "shortName": "item_invis_sword",
    "longName": "Shadow Blade",
    "cost": null
  },
  "153": {
    "shortName": "item_recipe_sange_and_yasha",
    "longName": "",
    "cost": null
  },
  "154": {
    "shortName": "item_sange_and_yasha",
    "longName": "Sange and Yasha",
    "cost": null
  },
  "155": {
    "shortName": "item_recipe_satanic",
    "longName": "Satanic Recipe",
    "cost": null
  },
  "156": {
    "shortName": "item_satanic",
    "longName": "Satanic",
    "cost": null
  },
  "157": {
    "shortName": "item_recipe_mjollnir",
    "longName": "Mjollnir Recipe",
    "cost": null
  },
  "158": {
    "shortName": "item_mjollnir",
    "longName": "Mjollnir",
    "cost": null
  },
  "159": {
    "shortName": "item_recipe_skadi",
    "longName": "Eye of Skadi Recipe",
    "cost": null
  },
  "160": {
    "shortName": "item_skadi",
    "longName": "Eye of Skadi",
    "cost": null
  },
  "161": {
    "shortName": "item_recipe_sange",
    "longName": "Sange Recipe",
    "cost": null
  },
  "162": {
    "shortName": "item_sange",
    "longName": "Sange",
    "cost": null
  },
  "163": {
    "shortName": "item_recipe_helm_of_the_dominator",
    "longName": "Helm of the Dominator Recipe",
    "cost": null
  },
  "164": {
    "shortName": "item_helm_of_the_dominator",
    "longName": "Helm of the Dominator",
    "cost": null
  },
  "165": {
    "shortName": "item_recipe_maelstrom",
    "longName": "Maelstrom Recipe",
    "cost": null
  },
  "166": {
    "shortName": "item_maelstrom",
    "longName": "Maelstrom",
    "cost": null
  },
  "167": {
    "shortName": "item_recipe_desolator",
    "longName": "",
    "cost": null
  },
  "168": {
    "shortName": "item_desolator",
    "longName": "Desolator",
    "cost": null
  },
  "169": {
    "shortName": "item_recipe_yasha",
    "longName": "Yasha Recipe",
    "cost": null
  },
  "170": {
    "shortName": "item_yasha",
    "longName": "Yasha",
    "cost": null
  },
  "171": {
    "shortName": "item_recipe_mask_of_madness",
    "longName": "Mask of Madness Recipe",
    "cost": null
  },
  "172": {
    "shortName": "item_mask_of_madness",
    "longName": "Mask of Madness",
    "cost": null
  },
  "173": {
    "shortName": "item_recipe_diffusal_blade",
    "longName": "Diffusal Blade Recipe",
    "cost": null
  },
  "174": {
    "shortName": "item_diffusal_blade",
    "longName": "Diffusal Blade",
    "cost": null
  },
  "175": {
    "shortName": "item_recipe_ethereal_blade",
    "longName": "Ethereal Blade Recipe",
    "cost": null
  },
  "176": {
    "shortName": "item_ethereal_blade",
    "longName": "Ethereal Blade",
    "cost": null
  },
  "177": {
    "shortName": "item_recipe_soul_ring",
    "longName": "Soul Ring Recipe",
    "cost": null
  },
  "178": {
    "shortName": "item_soul_ring",
    "longName": "Soul Ring",
    "cost": null
  },
  "179": {
    "shortName": "item_recipe_arcane_boots",
    "longName": "Arcane Boots Recipe",
    "cost": null
  },
  "180": {
    "shortName": "item_arcane_boots",
    "longName": "Arcane Boots",
    "cost": null
  },
  "181": {
    "shortName": "item_orb_of_venom",
    "longName": "Orb of Venom",
    "cost": null
  },
  "182": {
    "shortName": "item_stout_shield",
    "longName": "Stout Shield",
    "cost": null
  },
  "183": {
    "shortName": "item_recipe_invis_sword",
    "longName": "",
    "cost": null
  },
  "184": {
    "shortName": "item_recipe_ancient_janggo",
    "longName": "Drum of Endurance Recipe",
    "cost": null
  },
  "185": {
    "shortName": "item_ancient_janggo",
    "longName": "Drum of Endurance",
    "cost": null
  },
  "186": {
    "shortName": "item_recipe_medallion_of_courage",
    "longName": "",
    "cost": null
  },
  "187": {
    "shortName": "item_medallion_of_courage",
    "longName": "Medallion of Courage",
    "cost": null
  },
  "188": {
    "shortName": "item_smoke_of_deceit",
    "longName": "Smoke of Deceit",
    "cost": null
  },
  "189": {
    "shortName": "item_recipe_veil_of_discord",
    "longName": "Veil of Discord Recipe",
    "cost": null
  },
  "190": {
    "shortName": "item_veil_of_discord",
    "longName": "Veil of Discord",
    "cost": null
  },
  "191": {
    "shortName": "item_recipe_necronomicon_2",
    "longName": "",
    "cost": null
  },
  "192": {
    "shortName": "item_recipe_necronomicon_3",
    "longName": "",
    "cost": null
  },
  "193": {
    "shortName": "item_necronomicon_2",
    "longName": "Necronomicon 2",
    "cost": null
  },
  "194": {
    "shortName": "item_necronomicon_3",
    "longName": "Necronomicon 3",
    "cost": null
  },
  "195": {
    "shortName": "item_recipe_diffusal_blade",
    "longName": "Diffusal Blade 2 Recipe",
    "cost": 600
  },
  "196": {
    "shortName": "item_diffusal_blade_2",
    "longName": "Diffusal Blade 2",
    "cost": 2825
  },
  "197": {
    "shortName": "item_recipe_dagon_2",
    "longName": "",
    "cost": null
  },
  "198": {
    "shortName": "item_recipe_dagon_3",
    "longName": "",
    "cost": null
  },
  "199": {
    "shortName": "item_recipe_dagon_4",
    "longName": "",
    "cost": null
  },
  "200": {
    "shortName": "item_recipe_dagon_5",
    "longName": "",
    "cost": null
  },
  "201": {
    "shortName": "item_dagon_2",
    "longName": "Dagon",
    "cost": null
  },
  "202": {
    "shortName": "item_dagon_3",
    "longName": "Dagon",
    "cost": null
  },
  "203": {
    "shortName": "item_dagon_4",
    "longName": "Dagon",
    "cost": null
  },
  "204": {
    "shortName": "item_dagon_5",
    "longName": "Dagon",
    "cost": null
  },
  "205": {
    "shortName": "item_recipe_rod_of_atos",
    "longName": "Rod of Atos Recipe",
    "cost": null
  },
  "206": {
    "shortName": "item_rod_of_atos",
    "longName": "Rod of Atos",
    "cost": null
  },
  "207": {
    "shortName": "item_recipe_abyssal_blade",
    "longName": "Abyssal Blade Recipe",
    "cost": null
  },
  "208": {
    "shortName": "item_abyssal_blade",
    "longName": "Abyssal Blade",
    "cost": null
  },
  "209": {
    "shortName": "item_recipe_heavens_halberd",
    "longName": "Heaven's Halberd Recipe",
    "cost": null
  },
  "210": {
    "shortName": "item_heavens_halberd",
    "longName": "Heaven's Halberd",
    "cost": null
  },
  "211": {
    "shortName": "item_recipe_ring_of_aquila",
    "longName": "",
    "cost": null
  },
  "212": {
    "shortName": "item_ring_of_aquila",
    "longName": "Ring of Aquila",
    "cost": null
  },
  "213": {
    "shortName": "item_recipe_tranquil_boots",
    "longName": "Tranquil Boots Recipe",
    "cost": null
  },
  "214": {
    "shortName": "item_tranquil_boots",
    "longName": "Tranquil Boots",
    "cost": null
  },
  "215": {
    "shortName": "item_shadow_amulet",
    "longName": "Shadow Amulet",
    "cost": null
  },
  "216": {
    "shortName": "item_enchanted_mango",
    "longName": "Enchanted Mango",
    "cost": null
  },
  "217": {
    "shortName": "item_recipe_ward_dispenser",
    "longName": "",
    "cost": null
  },
  "218": {
    "shortName": "item_ward_dispenser",
    "longName": "Observer and Sentry Wards",
    "cost": null
  },
  "219": {
    "shortName": "item_recipe_travel_boots_2",
    "longName": "",
    "cost": null
  },
  "220": {
    "shortName": "item_travel_boots_2",
    "longName": "Boots of Travel 2",
    "cost": null
  },
  "221": {
    "shortName": "item_recipe_lotus_orb",
    "longName": "Lotus Orb Recipe",
    "cost": null
  },
  "222": {
    "shortName": "item_recipe_meteor_hammer",
    "longName": "Meteor Hammer Recipe",
    "cost": null
  },
  "223": {
    "shortName": "item_meteor_hammer",
    "longName": "Meteor Hammer",
    "cost": null
  },
  "224": {
    "shortName": "item_recipe_nullifier",
    "longName": "Nullifier Recipe",
    "cost": null
  },
  "225": {
    "shortName": "item_nullifier",
    "longName": "Nullifier",
    "cost": null
  },
  "226": {
    "shortName": "item_lotus_orb",
    "longName": "Lotus Orb",
    "cost": null
  },
  "227": {
    "shortName": "item_recipe_solar_crest",
    "longName": "Solar Crest Recipe",
    "cost": null
  },
  "228": {
    "shortName": "item_recipe_octarine_core",
    "longName": "Octarine Core Recipe",
    "cost": null
  },
  "229": {
    "shortName": "item_solar_crest",
    "longName": "Solar Crest",
    "cost": null
  },
  "230": {
    "shortName": "item_recipe_guardian_greaves",
    "longName": "Guardian Greaves Recipe",
    "cost": null
  },
  "231": {
    "shortName": "item_guardian_greaves",
    "longName": "Guardian Greaves",
    "cost": null
  },
  "232": {
    "shortName": "item_aether_lens",
    "longName": "Aether Lens",
    "cost": null
  },
  "233": {
    "shortName": "item_recipe_aether_lens",
    "longName": "Aether Lens Recipe",
    "cost": null
  },
  "234": {
    "shortName": "item_recipe_dragon_lance",
    "longName": "Dragon Lance Recipe",
    "cost": null
  },
  "235": {
    "shortName": "item_octarine_core",
    "longName": "Octarine Core",
    "cost": null
  },
  "236": {
    "shortName": "item_dragon_lance",
    "longName": "Dragon Lance",
    "cost": null
  },
  "237": {
    "shortName": "item_faerie_fire",
    "longName": "Faerie Fire",
    "cost": null
  },
  "238": {
    "shortName": "item_recipe_iron_talon",
    "longName": "Iron Talon Recipe",
    "cost": null
  },
  "239": {
    "shortName": "item_iron_talon",
    "longName": "Iron Talon",
    "cost": null
  },
  "240": {
    "shortName": "item_blight_stone",
    "longName": "Orb of Blight",
    "cost": null
  },
  "241": {
    "shortName": "item_tango_single",
    "longName": "Tango (Shared)",
    "cost": null
  },
  "242": {
    "shortName": "item_crimson_guard",
    "longName": "Crimson Guard",
    "cost": null
  },
  "243": {
    "shortName": "item_recipe_crimson_guard",
    "longName": "Crimson Guard Recipe",
    "cost": null
  },
  "244": {
    "shortName": "item_wind_lace",
    "longName": "Wind Lace",
    "cost": null
  },
  "245": {
    "shortName": "item_recipe_bloodthorn",
    "longName": "Bloodthorn Recipe",
    "cost": null
  },
  "246": {
    "shortName": "item_recipe_moon_shard",
    "longName": "",
    "cost": null
  },
  "247": {
    "shortName": "item_moon_shard",
    "longName": "Moon Shard",
    "cost": null
  },
  "248": {
    "shortName": "item_recipe_silver_edge",
    "longName": "Silver Edge Recipe",
    "cost": null
  },
  "249": {
    "shortName": "item_silver_edge",
    "longName": "Silver Edge",
    "cost": null
  },
  "250": {
    "shortName": "item_bloodthorn",
    "longName": "Bloodthorn",
    "cost": null
  },
  "251": {
    "shortName": "item_recipe_echo_sabre",
    "longName": "",
    "cost": null
  },
  "252": {
    "shortName": "item_echo_sabre",
    "longName": "Echo Sabre",
    "cost": null
  },
  "253": {
    "shortName": "item_recipe_glimmer_cape",
    "longName": "Glimmer Cape Recipe",
    "cost": null
  },
  "254": {
    "shortName": "item_glimmer_cape",
    "longName": "Glimmer Cape",
    "cost": null
  },
  "255": {
    "shortName": "item_recipe_aeon_disk",
    "longName": "Aeon Disk Recipe",
    "cost": null
  },
  "256": {
    "shortName": "item_aeon_disk",
    "longName": "Aeon Disk",
    "cost": null
  },
  "257": {
    "shortName": "item_tome_of_knowledge",
    "longName": "Tome of Knowledge",
    "cost": null
  },
  "258": {
    "shortName": "item_recipe_kaya",
    "longName": "Kaya Recipe",
    "cost": null
  },
  "259": {
    "shortName": "item_kaya",
    "longName": "Kaya",
    "cost": null
  },
  "260": {
    "shortName": "item_refresher_shard",
    "longName": "Refresher Shard",
    "cost": null
  },
  "261": {
    "shortName": "item_crown",
    "longName": "Crown",
    "cost": null
  },
  "262": {
    "shortName": "item_recipe_hurricane_pike",
    "longName": "Hurricane Pike Recipe",
    "cost": null
  },
  "263": {
    "shortName": "item_hurricane_pike",
    "longName": "Hurricane Pike",
    "cost": null
  },
  "264": {
    "shortName": "item_banana",
    "longName": "Banana",
    "cost": null
  },
  "265": {
    "shortName": "item_infused_raindrop",
    "longName": "Infused Raindrops",
    "cost": null
  },
  "266": {
    "shortName": "item_recipe_spirit_vessel",
    "longName": "Spirit Vessel Recipe",
    "cost": null
  },
  "267": {
    "shortName": "item_spirit_vessel",
    "longName": "Spirit Vessel",
    "cost": null
  },
  "268": {
    "shortName": "item_recipe_holy_locket",
    "longName": "Holy Locket Recipe",
    "cost": null
  },
  "269": {
    "shortName": "item_holy_locket",
    "longName": "Holy Locket",
    "cost": null
  },
  "270": {
    "shortName": "item_recipe_ultimate_scepter_2",
    "longName": "Aghanim's Blessing Recipe",
    "cost": null
  },
  "271": {
    "shortName": "item_ultimate_scepter_2",
    "longName": "Aghanim's Blessing",
    "cost": null
  },
  "272": {
    "shortName": "item_recipe_kaya_and_sange",
    "longName": "Kaya and Sange Recipe",
    "cost": null
  },
  "273": {
    "shortName": "item_kaya_and_sange",
    "longName": "Kaya and Sange",
    "cost": null
  },
  "274": {
    "shortName": "item_recipe_yasha_and_kaya",
    "longName": "Yasha and Kaya Recipe",
    "cost": null
  },
  "275": {
    "shortName": "item_recipe_trident",
    "longName": "Trident Recipe",
    "cost": null
  },
  "276": {
    "shortName": "item_combo_breaker",
    "longName": "",
    "cost": null
  },
  "277": {
    "shortName": "item_yasha_and_kaya",
    "longName": "Yasha and Kaya",
    "cost": null
  },
  "279": {
    "shortName": "item_ring_of_tarrasque",
    "longName": "Ring of Tarrasque",
    "cost": null
  },
  "286": {
    "shortName": "item_flying_courier",
    "longName": "Flying Courier",
    "cost": null
  },
  "287": {
    "shortName": "item_keen_optic",
    "longName": "Keen Optic",
    "cost": null
  },
  "288": {
    "shortName": "item_grove_bow",
    "longName": "Grove Bow",
    "cost": null
  },
  "289": {
    "shortName": "item_quickening_charm",
    "longName": "Quickening Charm",
    "cost": null
  },
  "290": {
    "shortName": "item_philosophers_stone",
    "longName": "Philosopher's Stone",
    "cost": null
  },
  "291": {
    "shortName": "item_force_boots",
    "longName": "Force Boots",
    "cost": null
  },
  "292": {
    "shortName": "item_desolator_2",
    "longName": "Stygian Desolator",
    "cost": null
  },
  "293": {
    "shortName": "item_phoenix_ash",
    "longName": "Phoenix Ash",
    "cost": null
  },
  "294": {
    "shortName": "item_seer_stone",
    "longName": "Seer Stone",
    "cost": null
  },
  "295": {
    "shortName": "item_greater_mango",
    "longName": "",
    "cost": null
  },
  "297": {
    "shortName": "item_vampire_fangs",
    "longName": "Vampire Fangs",
    "cost": null
  },
  "298": {
    "shortName": "item_craggy_coat",
    "longName": "Craggy Coat",
    "cost": null
  },
  "299": {
    "shortName": "item_greater_faerie_fire",
    "longName": "Greater Faerie Fire",
    "cost": null
  },
  "300": {
    "shortName": "item_timeless_relic",
    "longName": "Timeless Relic",
    "cost": null
  },
  "301": {
    "shortName": "item_mirror_shield",
    "longName": "Mirror Shield",
    "cost": null
  },
  "302": {
    "shortName": "item_elixer",
    "longName": "Elixir",
    "cost": null
  },
  "303": {
    "shortName": "item_recipe_ironwood_tree",
    "longName": "Ironwood Tree Recipe",
    "cost": null
  },
  "304": {
    "shortName": "item_ironwood_tree",
    "longName": "Ironwood Tree",
    "cost": null
  },
  "305": {
    "shortName": "item_royal_jelly",
    "longName": "Royal Jelly",
    "cost": null
  },
  "306": {
    "shortName": "item_pupils_gift",
    "longName": "Pupil's Gift",
    "cost": null
  },
  "307": {
    "shortName": "item_tome_of_aghanim",
    "longName": "Tome of Aghanim",
    "cost": null
  },
  "308": {
    "shortName": "item_repair_kit",
    "longName": "Repair Kit",
    "cost": null
  },
  "309": {
    "shortName": "item_mind_breaker",
    "longName": "Mind Breaker",
    "cost": null
  },
  "310": {
    "shortName": "item_third_eye",
    "longName": "Third Eye",
    "cost": null
  },
  "311": {
    "shortName": "item_spell_prism",
    "longName": "Spell Prism",
    "cost": null
  },
  "312": {
    "shortName": "item_horizon",
    "longName": "",
    "cost": null
  },
  "313": {
    "shortName": "item_fusion_rune",
    "longName": "Fusion Rune",
    "cost": null
  },
  "317": {
    "shortName": "item_recipe_fallen_sky",
    "longName": "Recipe: Fallen Sky",
    "cost": null
  },
  "325": {
    "shortName": "item_princes_knife",
    "longName": "Prince's Knife",
    "cost": null
  },
  "326": {
    "shortName": "item_spider_legs",
    "longName": "Spider Legs",
    "cost": null
  },
  "327": {
    "shortName": "item_helm_of_the_undying",
    "longName": "Helm of the Undying",
    "cost": null
  },
  "328": {
    "shortName": "item_mango_tree",
    "longName": "Mango Tree",
    "cost": null
  },
  "329": {
    "shortName": "item_recipe_vambrace",
    "longName": "Recipe: Vambrace",
    "cost": null
  },
  "330": {
    "shortName": "item_witless_shako",
    "longName": "Witless Shako",
    "cost": null
  },
  "331": {
    "shortName": "item_vambrace",
    "longName": "Vambrace",
    "cost": null
  },
  "334": {
    "shortName": "item_imp_claw",
    "longName": "Imp Claw",
    "cost": null
  },
  "335": {
    "shortName": "item_flicker",
    "longName": "Flicker",
    "cost": null
  },
  "336": {
    "shortName": "item_spy_gadget",
    "longName": "Telescope",
    "cost": null
  },
  "349": {
    "shortName": "item_arcane_ring",
    "longName": "Arcane Ring",
    "cost": null
  },
  "354": {
    "shortName": "item_ocean_heart",
    "longName": "Ocean Heart",
    "cost": null
  },
  "355": {
    "shortName": "item_broom_handle",
    "longName": "Broom Handle",
    "cost": null
  },
  "356": {
    "shortName": "item_trusty_shovel",
    "longName": "Trusty Shovel",
    "cost": null
  },
  "357": {
    "shortName": "item_nether_shawl",
    "longName": "Nether Shawl",
    "cost": null
  },
  "358": {
    "shortName": "item_dragon_scale",
    "longName": "Dragon Scale",
    "cost": null
  },
  "359": {
    "shortName": "item_essence_ring",
    "longName": "Essence Ring",
    "cost": null
  },
  "360": {
    "shortName": "item_clumsy_net",
    "longName": "Clumsy Net",
    "cost": null
  },
  "361": {
    "shortName": "item_enchanted_quiver",
    "longName": "Enchanted Quiver",
    "cost": null
  },
  "362": {
    "shortName": "item_ninja_gear",
    "longName": "Ninja Gear",
    "cost": null
  },
  "363": {
    "shortName": "item_illusionsts_cape",
    "longName": "Illusionist's Cape",
    "cost": null
  },
  "364": {
    "shortName": "item_havoc_hammer",
    "longName": "Havoc Hammer",
    "cost": null
  },
  "365": {
    "shortName": "item_panic_button",
    "longName": "Magic Lamp",
    "cost": null
  },
  "366": {
    "shortName": "item_apex",
    "longName": "Apex",
    "cost": null
  },
  "367": {
    "shortName": "item_ballista",
    "longName": "Ballista",
    "cost": null
  },
  "368": {
    "shortName": "item_woodland_striders",
    "longName": "Woodland Striders",
    "cost": null
  },
  "369": {
    "shortName": "item_trident",
    "longName": "Trident",
    "cost": null
  },
  "370": {
    "shortName": "item_demonicon",
    "longName": "Book of the Dead",
    "cost": null
  },
  "371": {
    "shortName": "item_fallen_sky",
    "longName": "Fallen Sky",
    "cost": null
  },
  "372": {
    "shortName": "item_pirate_hat",
    "longName": "Pirate Hat",
    "cost": null
  },
  "373": {
    "shortName": "item_dimensional_doorway",
    "longName": "",
    "cost": null
  },
  "374": {
    "shortName": "item_ex_machina",
    "longName": "Ex Machina",
    "cost": null
  },
  "375": {
    "shortName": "item_faded_broach",
    "longName": "Faded Broach",
    "cost": null
  },
  "376": {
    "shortName": "item_paladin_sword",
    "longName": "Paladin Sword",
    "cost": null
  },
  "377": {
    "shortName": "item_minotaur_horn",
    "longName": "Minotaur Horn",
    "cost": null
  },
  "378": {
    "shortName": "item_orb_of_destruction",
    "longName": "Orb of Destruction",
    "cost": null
  },
  "379": {
    "shortName": "item_the_leveller",
    "longName": "The Leveller",
    "cost": null
  },
  "381": {
    "shortName": "item_titan_sliver",
    "longName": "Titan Sliver",
    "cost": null
  },
  "473": {
    "shortName": "item_voodoo_mask",
    "longName": "Voodoo Mask",
    "cost": null
  },
  "485": {
    "shortName": "item_blitz_knuckles",
    "longName": "Blitz Knuckles",
    "cost": null
  },
  "533": {
    "shortName": "item_recipe_witch_blade",
    "longName": "Witch Blade Recipe",
    "cost": null
  },
  "534": {
    "shortName": "item_witch_blade",
    "longName": "Witch Blade",
    "cost": null
  },
  "565": {
    "shortName": "item_chipped_vest",
    "longName": "Chipped Vest",
    "cost": null
  },
  "566": {
    "shortName": "item_wizard_glass",
    "longName": "",
    "cost": null
  },
  "569": {
    "shortName": "item_orb_of_corrosion",
    "longName": "Orb of Corrosion",
    "cost": null
  },
  "570": {
    "shortName": "item_gloves_of_travel",
    "longName": "",
    "cost": null
  },
  "571": {
    "shortName": "item_trickster_cloak",
    "longName": "Trickster Cloak",
    "cost": null
  },
  "573": {
    "shortName": "item_elven_tunic",
    "longName": "Elven Tunic",
    "cost": null
  },
  "574": {
    "shortName": "item_cloak_of_flames",
    "longName": "Cloak of Flames",
    "cost": null
  },
  "575": {
    "shortName": "item_venom_gland",
    "longName": "",
    "cost": null
  },
  "576": {
    "shortName": "item_gladiator_helm",
    "longName": "",
    "cost": null
  },
  "577": {
    "shortName": "item_possessed_mask",
    "longName": "Possessed Mask",
    "cost": null
  },
  "578": {
    "shortName": "item_ancient_perseverance",
    "longName": "",
    "cost": null
  },
  "582": {
    "shortName": "item_oakheart",
    "longName": "",
    "cost": null
  },
  "585": {
    "shortName": "item_stormcrafter",
    "longName": "Stormcrafter",
    "cost": null
  },
  "588": {
    "shortName": "item_overflowing_elixir",
    "longName": "",
    "cost": null
  },
  "589": {
    "shortName": "item_mysterious_hat",
    "longName": "Fairy's Trinket",
    "cost": null
  },
  "593": {
    "shortName": "item_fluffy_hat",
    "longName": "Fluffy Hat",
    "cost": null
  },
  "596": {
    "shortName": "item_falcon_blade",
    "longName": "Falcon Blade",
    "cost": null
  },
  "597": {
    "shortName": "item_recipe_mage_slayer",
    "longName": "Mage Slayer Recipe",
    "cost": null
  },
  "598": {
    "shortName": "item_mage_slayer",
    "longName": "Mage Slayer",
    "cost": null
  },
  "599": {
    "shortName": "item_recipe_falcon_blade",
    "longName": "Falcon Blade Recipe",
    "cost": null
  },
  "600": {
    "shortName": "item_overwhelming_blink",
    "longName": "Overwhelming Blink",
    "cost": null
  },
  "603": {
    "shortName": "item_swift_blink",
    "longName": "Swift Blink",
    "cost": null
  },
  "604": {
    "shortName": "item_arcane_blink",
    "longName": "Arcane Blink",
    "cost": null
  },
  "606": {
    "shortName": "item_recipe_arcane_blink",
    "longName": "Arcane Blink Recipe",
    "cost": null
  },
  "607": {
    "shortName": "item_recipe_swift_blink",
    "longName": "Swift Blink Recipe",
    "cost": null
  },
  "608": {
    "shortName": "item_recipe_overwhelming_blink",
    "longName": "Overwhelming Blink Recipe",
    "cost": null
  },
  "609": {
    "shortName": "item_aghanims_shard",
    "longName": "Aghanim's Shard",
    "cost": null
  },
  "610": {
    "shortName": "item_wind_waker",
    "longName": "Wind Waker",
    "cost": null
  },
  "612": {
    "shortName": "item_recipe_wind_waker",
    "longName": "Wind Waker Recipe",
    "cost": null
  },
  "633": {
    "shortName": "item_recipe_helm_of_the_overlord",
    "longName": "Helm of the Overlord Recipe",
    "cost": null
  },
  "635": {
    "shortName": "item_helm_of_the_overlord",
    "longName": "Helm of the Overlord",
    "cost": null
  },
  "637": {
    "shortName": "item_star_mace",
    "longName": "",
    "cost": null
  },
  "638": {
    "shortName": "item_penta_edged_sword",
    "longName": "Penta-Edged Sword",
    "cost": null
  },
  "640": {
    "shortName": "item_recipe_orb_of_corrosion",
    "longName": "Orb of Corrosion Recipe",
    "cost": null
  },
  "653": {
    "shortName": "item_recipe_grandmasters_glaive",
    "longName": "",
    "cost": null
  },
  "655": {
    "shortName": "item_grandmasters_glaive",
    "longName": "",
    "cost": null
  },
  "674": {
    "shortName": "item_warhammer",
    "longName": "",
    "cost": null
  },
  "675": {
    "shortName": "item_psychic_headband",
    "longName": "Psychic Headband",
    "cost": null
  },
  "676": {
    "shortName": "item_ceremonial_robe",
    "longName": "Ceremonial Robe",
    "cost": null
  },
  "677": {
    "shortName": "item_book_of_shadows",
    "longName": "Book of Shadows",
    "cost": null
  },
  "678": {
    "shortName": "item_giants_ring",
    "longName": "Giant's Ring",
    "cost": null
  },
  "679": {
    "shortName": "item_vengeances_shadow",
    "longName": "Shadow of Vengeance",
    "cost": null
  },
  "680": {
    "shortName": "item_bullwhip",
    "longName": "Bullwhip",
    "cost": null
  },
  "686": {
    "shortName": "item_quicksilver_amulet",
    "longName": "Quicksilver Amulet",
    "cost": null
  },
  "691": {
    "shortName": "item_recipe_eternal_shroud",
    "longName": "Eternal Shroud Recipe",
    "cost": null
  },
  "692": {
    "shortName": "item_eternal_shroud",
    "longName": "Eternal Shroud",
    "cost": null
  },
  "725": {
    "shortName": "item_aghanims_shard_roshan",
    "longName": "Aghanim's Shard - Consumable",
    "cost": null
  },
  "727": {
    "shortName": "item_ultimate_scepter_roshan",
    "longName": "Aghanim's Blessing - Roshan",
    "cost": null
  },
  "731": {
    "shortName": "item_satchel",
    "longName": "",
    "cost": null
  },
  "824": {
    "shortName": "item_assassins_dagger",
    "longName": "",
    "cost": null
  },
  "825": {
    "shortName": "item_ascetic_cap",
    "longName": "Ascetic's Cap",
    "cost": null
  },
  "826": {
    "shortName": "item_sample_picker",
    "longName": "",
    "cost": null
  },
  "827": {
    "shortName": "item_icarus_wings",
    "longName": "",
    "cost": null
  },
  "828": {
    "shortName": "item_misericorde",
    "longName": "Brigand's Blade",
    "cost": null
  },
  "829": {
    "shortName": "item_force_field",
    "longName": "Arcanist's Armor",
    "cost": null
  },
  "833": {
    "shortName": "item_recipe_tenderizer",
    "longName": "Recipe: Bruiser's Maul",
    "cost": 425
  },
  "834": {
    "shortName": "item_black_powder_bag",
    "longName": "Blast Rig",
    "cost": null
  },
  "835": {
    "shortName": "item_paintball",
    "longName": "Fae Grenade",
    "cost": null
  },
  "836": {
    "shortName": "item_light_robes",
    "longName": "",
    "cost": null
  },
  "837": {
    "shortName": "item_heavy_blade",
    "longName": "Witchbane",
    "cost": null
  },
  "838": {
    "shortName": "item_unstable_wand",
    "longName": "Pig Pole",
    "cost": null
  },
  "839": {
    "shortName": "item_fortitude_ring",
    "longName": "",
    "cost": null
  },
  "840": {
    "shortName": "item_pogo_stick",
    "longName": "Tumbler's Toy",
    "cost": null
  },
  "849": {
    "shortName": "item_mechanical_arm",
    "longName": "",
    "cost": null
  },
  "859": {
    "shortName": "item_recipe_voidwalker_scythe",
    "longName": "Recipe: Voidwalker Scythe",
    "cost": null
  },
  "904": {
    "shortName": "item_voidwalker_scythe",
    "longName": "Voidwalker Scythe",
    "cost": 3900
  },
  "906": {
    "shortName": "item_tenderizer",
    "longName": "Bruiser's Maul",
    "cost": 6100
  },
  "907": {
    "shortName": "item_recipe_wraith_pact",
    "longName": "",
    "cost": null
  },
  "908": {
    "shortName": "item_wraith_pact",
    "longName": "Wraith Pact",
    "cost": null
  },
  "910": {
    "shortName": "item_recipe_revenants_brooch",
    "longName": "Revenant's Brooch Recipe",
    "cost": null
  },
  "911": {
    "shortName": "item_revenants_brooch",
    "longName": "Revenant's Brooch",
    "cost": null
  },
  "928": {
    "shortName": "item_recipe_eagle_eye",
    "longName": "Recipe: Eagle Eye",
    "cost": null
  },
  "929": {
    "shortName": "item_eagle_eye",
    "longName": "Eagle Eye",
    "cost": 3700
  },
  "930": {
    "shortName": "item_recipe_boots_of_bearing",
    "longName": "Boots of Bearing Recipe",
    "cost": null
  },
  "931": {
    "shortName": "item_boots_of_bearing",
    "longName": "Boots of Bearing",
    "cost": null
  },
  "938": {
    "shortName": "item_slime_vial",
    "longName": "",
    "cost": null
  },
  "939": {
    "shortName": "item_harpoon",
    "longName": "Harpoon",
    "cost": null
  },
  "940": {
    "shortName": "item_wand_of_the_brine",
    "longName": "Wand of the Brine",
    "cost": null
  },
  "945": {
    "shortName": "item_seeds_of_serenity",
    "longName": "Seeds of Serenity",
    "cost": null
  },
  "946": {
    "shortName": "item_lance_of_pursuit",
    "longName": "Lance of Pursuit",
    "cost": null
  },
  "947": {
    "shortName": "item_occult_bracelet",
    "longName": "Occult Bracelet",
    "cost": null
  },
  "948": {
    "shortName": "item_tome_of_omniscience",
    "longName": "",
    "cost": null
  },
  "949": {
    "shortName": "item_ogre_seal_totem",
    "longName": "Ogre Seal Totem",
    "cost": null
  },
  "950": {
    "shortName": "item_defiant_shell",
    "longName": "Defiant Shell",
    "cost": null
  },
  "964": {
    "shortName": "item_diffusal_blade_2",
    "longName": "Diffusal Blade",
    "cost": 5500
  },
  "965": {
    "shortName": "item_recipe_diffusal_blade_2",
    "longName": "Recipe: Diffusal Blade",
    "cost": 200
  },
  "968": {
    "shortName": "item_arcane_scout",
    "longName": "",
    "cost": null
  },
  "969": {
    "shortName": "item_barricade",
    "longName": "",
    "cost": null
  },
  "990": {
    "shortName": "item_eye_of_the_vizier",
    "longName": "Eye of the Vizier",
    "cost": null
  },
  "998": {
    "shortName": "item_manacles_of_power",
    "longName": "",
    "cost": null
  },
  "1000": {
    "shortName": "item_bottomless_chalice",
    "longName": "",
    "cost": null
  },
  "1001": {
    "shortName": "item_mystery_hook",
    "longName": "DOTA_Tooltip_Ability_item_mystery_hook",
    "cost": null
  },
  "1002": {
    "shortName": "item_mystery_arrow",
    "longName": "DOTA_Tooltip_Ability_item_mystery_arrow",
    "cost": null
  },
  "1003": {
    "shortName": "item_mystery_missile",
    "longName": "DOTA_Tooltip_Ability_item_mystery_missile",
    "cost": null
  },
  "1004": {
    "shortName": "item_mystery_toss",
    "longName": "DOTA_Tooltip_Ability_item_mystery_toss",
    "cost": null
  },
  "1005": {
    "shortName": "item_mystery_vacuum",
    "longName": "DOTA_Tooltip_Ability_item_mystery_vacuum",
    "cost": null
  },
  "1006": {
    "shortName": "item_halloween_rapier",
    "longName": "DOTA_Tooltip_Ability_item_halloween_rapier",
    "cost": 6200
  },
  "1007": {
    "shortName": "item_greevil_whistle",
    "longName": "Greevil Whistle",
    "cost": null
  },
  "1008": {
    "shortName": "item_greevil_whistle_toggle",
    "longName": "Greevil Whistle",
    "cost": null
  },
  "1009": {
    "shortName": "item_present",
    "longName": "A Gift!",
    "cost": null
  },
  "1010": {
    "shortName": "item_winter_stocking",
    "longName": "Xmas Stocking",
    "cost": null
  },
  "1011": {
    "shortName": "item_winter_skates",
    "longName": "Speed Skates",
    "cost": null
  },
  "1012": {
    "shortName": "item_winter_cake",
    "longName": "Fruit-bit Cake",
    "cost": null
  },
  "1013": {
    "shortName": "item_winter_cookie",
    "longName": "Wizard Cookie",
    "cost": null
  },
  "1014": {
    "shortName": "item_winter_coco",
    "longName": "Cocoa with Marshmallows",
    "cost": null
  },
  "1015": {
    "shortName": "item_winter_ham",
    "longName": "Clove Studded Ham",
    "cost": null
  },
  "1016": {
    "shortName": "item_winter_kringle",
    "longName": "Kringle",
    "cost": null
  },
  "1017": {
    "shortName": "item_wand_of_sanctitude",
    "longName": "",
    "cost": null
  },
  "1018": {
    "shortName": "item_winter_greevil_treat",
    "longName": "Greevil Treat",
    "cost": null
  },
  "1019": {
    "shortName": "item_winter_greevil_garbage",
    "longName": "Greevil Chow",
    "cost": null
  },
  "1020": {
    "shortName": "item_winter_greevil_chewy",
    "longName": "Greevil Blink Bone",
    "cost": null
  },
  "1021": {
    "shortName": "item_river_painter",
    "longName": "River Vial: Chrome",
    "cost": null
  },
  "1022": {
    "shortName": "item_river_painter2",
    "longName": "River Vial: Dry",
    "cost": null
  },
  "1023": {
    "shortName": "item_river_painter3",
    "longName": "River Vial: Slime",
    "cost": null
  },
  "1024": {
    "shortName": "item_river_painter4",
    "longName": "River Vial: Oil",
    "cost": null
  },
  "1025": {
    "shortName": "item_river_painter5",
    "longName": "River Vial: Electrified",
    "cost": null
  },
  "1026": {
    "shortName": "item_river_painter6",
    "longName": "River Vial: Potion",
    "cost": null
  },
  "1027": {
    "shortName": "item_river_painter7",
    "longName": "River Vial: Blood",
    "cost": null
  },
  "1028": {
    "shortName": "item_mutation_tombstone",
    "longName": "Tombstone",
    "cost": null
  },
  "1029": {
    "shortName": "item_super_blink",
    "longName": "",
    "cost": null
  },
  "1030": {
    "shortName": "item_pocket_tower",
    "longName": "Pocket Tower",
    "cost": null
  },
  "1032": {
    "shortName": "item_pocket_roshan",
    "longName": "Pocket Roshan",
    "cost": null
  },
  "1076": {
    "shortName": "item_specialists_array",
    "longName": "Specialist's Array",
    "cost": null
  },
  "1077": {
    "shortName": "item_dagger_of_ristul",
    "longName": "Dagger of Ristul",
    "cost": null
  },
  "1090": {
    "shortName": "item_muertas_gun",
    "longName": "Mercy & Grace",
    "cost": null
  },
  "1091": {
    "shortName": "item_samurai_tabi",
    "longName": "",
    "cost": null
  },
  "1092": {
    "shortName": "item_recipe_hermes_sandals",
    "longName": "",
    "cost": null
  },
  "1093": {
    "shortName": "item_hermes_sandals",
    "longName": "",
    "cost": null
  },
  "1094": {
    "shortName": "item_recipe_lunar_crest",
    "longName": "",
    "cost": null
  },
  "1095": {
    "shortName": "item_lunar_crest",
    "longName": "Lunar Crest",
    "cost": null
  },
  "1096": {
    "shortName": "item_recipe_disperser",
    "longName": "Disperser Recipe",
    "cost": null
  },
  "1097": {
    "shortName": "item_disperser",
    "longName": "Disperser",
    "cost": null
  },
  "1098": {
    "shortName": "item_recipe_samurai_tabi",
    "longName": "",
    "cost": null
  },
  "1099": {
    "shortName": "item_recipe_witches_switch",
    "longName": "",
    "cost": null
  },
  "1100": {
    "shortName": "item_witches_switch",
    "longName": "",
    "cost": null
  },
  "1101": {
    "shortName": "item_recipe_harpoon",
    "longName": "Harpoon Recipe",
    "cost": null
  },
  "1106": {
    "shortName": "item_recipe_phylactery",
    "longName": "Phylactery Recipe",
    "cost": null
  },
  "1107": {
    "shortName": "item_phylactery",
    "longName": "Phylactery",
    "cost": null
  },
  "1122": {
    "shortName": "item_diadem",
    "longName": "Diadem",
    "cost": null
  },
  "1123": {
    "shortName": "item_blood_grenade",
    "longName": "Blood Grenade",
    "cost": null
  },
  "1124": {
    "shortName": "item_spark_of_courage",
    "longName": "Spark of Courage",
    "cost": null
  },
  "1125": {
    "shortName": "item_cornucopia",
    "longName": "Cornucopia",
    "cost": null
  },
  "1127": {
    "shortName": "item_recipe_pavise",
    "longName": "Pavise Recipe",
    "cost": null
  },
  "1128": {
    "shortName": "item_pavise",
    "longName": "Pavise",
    "cost": null
  },
  "1154": {
    "shortName": "item_royale_with_cheese",
    "longName": "Block of Cheese",
    "cost": null
  },
  "1156": {
    "shortName": "item_ancient_guardian",
    "longName": "Ancient Guardian",
    "cost": null
  },
  "1157": {
    "shortName": "item_safety_bubble",
    "longName": "Safety Bubble",
    "cost": null
  },
  "1158": {
    "shortName": "item_whisper_of_the_dread",
    "longName": "Whisper of the Dread",
    "cost": null
  },
  "1159": {
    "shortName": "item_nemesis_curse",
    "longName": "Nemesis Curse",
    "cost": null
  },
  "1160": {
    "shortName": "item_avianas_feather",
    "longName": "Aviana's Feather",
    "cost": null
  },
  "1161": {
    "shortName": "item_unwavering_condition",
    "longName": "Unwavering Condition",
    "cost": null
  },
  "1164": {
    "shortName": "item_aetherial_halo",
    "longName": "",
    "cost": null
  },
  "1167": {
    "shortName": "item_light_collector",
    "longName": "Light Collector",
    "cost": null
  },
  "1168": {
    "shortName": "item_rattlecage",
    "longName": "Rattlecage",
    "cost": null
  },
  "1440": {
    "shortName": "item_black_grimoire",
    "longName": "Black Grimoire",
    "cost": null
  },
  "1441": {
    "shortName": "item_grisgris",
    "longName": "Gris-Gris",
    "cost": null
  },
  "1466": {
    "shortName": "item_gungir",
    "longName": "Gleipnir",
    "cost": null
  },
  "1565": {
    "shortName": "item_recipe_gungir",
    "longName": "Gleipnir Recipe",
    "cost": null
  },
  "1575": {
    "shortName": "item_orb_of_frost",
    "longName": "Orb of Frost",
    "cost": null
  },
  "1576": {
    "shortName": "item_enhancement_vast",
    "longName": "Vast",
    "cost": null
  },
  "1577": {
    "shortName": "item_enhancement_quickened",
    "longName": "Quickened",
    "cost": null
  },
  "1578": {
    "shortName": "item_cursed_circlet",
    "longName": "Accursed",
    "cost": null
  },
  "1579": {
    "shortName": "item_ogre_heart",
    "longName": "Restorative",
    "cost": null
  },
  "1580": {
    "shortName": "item_neutral_tabi",
    "longName": "Elusive",
    "cost": null
  },
  "1581": {
    "shortName": "item_enhancement_audacious",
    "longName": "Audacious",
    "cost": null
  },
  "1582": {
    "shortName": "item_hellbear_totem",
    "longName": "",
    "cost": null
  },
  "1583": {
    "shortName": "item_enhancement_mystical",
    "longName": "Mystical",
    "cost": null
  },
  "1584": {
    "shortName": "item_enhancement_alert",
    "longName": "Alert",
    "cost": null
  },
  "1585": {
    "shortName": "item_enhancement_brawny",
    "longName": "Brawny",
    "cost": null
  },
  "1586": {
    "shortName": "item_enhancement_tough",
    "longName": "Tough",
    "cost": null
  },
  "1587": {
    "shortName": "item_enhancement_feverish",
    "longName": "Feverish",
    "cost": null
  },
  "1588": {
    "shortName": "item_enhancement_fleetfooted",
    "longName": "Fleetfooted",
    "cost": null
  },
  "1589": {
    "shortName": "item_enhancement_crude",
    "longName": "Crude",
    "cost": null
  },
  "1590": {
    "shortName": "item_enhancement_boundless",
    "longName": "Boundless",
    "cost": null
  },
  "1591": {
    "shortName": "item_enhancement_wise",
    "longName": "Wise",
    "cost": null
  },
  "1592": {
    "shortName": "item_enhancement_timeless",
    "longName": "Timeless",
    "cost": null
  },
  "1593": {
    "shortName": "item_enhancement_greedy",
    "longName": "Greedy",
    "cost": null
  },
  "1594": {
    "shortName": "item_enhancement_vampiric",
    "longName": "Vampiric",
    "cost": null
  },
  "1595": {
    "shortName": "item_enhancement_keen_eyed",
    "longName": "Keen-eyed",
    "cost": null
  },
  "1596": {
    "shortName": "item_enhancement_evolved",
    "longName": "Evolved",
    "cost": null
  },
  "1597": {
    "shortName": "item_enhancement_titanic",
    "longName": "Titanic",
    "cost": null
  },
  "1598": {
    "shortName": "item_unrelenting_eye",
    "longName": "Unrelenting Eye",
    "cost": null
  },
  "1599": {
    "shortName": "item_mana_draught",
    "longName": "Mana Draught",
    "cost": null
  },
  "1600": {
    "shortName": "item_rippers_lash",
    "longName": "Ripper's Lash",
    "cost": null
  },
  "1601": {
    "shortName": "item_crippling_crossbow",
    "longName": "Crippling Crossbow",
    "cost": null
  },
  "1602": {
    "shortName": "item_gale_guard",
    "longName": "Gale Guard",
    "cost": null
  },
  "1603": {
    "shortName": "item_gunpowder_gauntlets",
    "longName": "Gunpowder Gauntlet",
    "cost": null
  },
  "1604": {
    "shortName": "item_searing_signet",
    "longName": "Searing Signet",
    "cost": null
  },
  "1605": {
    "shortName": "item_serrated_shiv",
    "longName": "Serrated Shiv",
    "cost": null
  },
  "1606": {
    "shortName": "item_polliwog_charm",
    "longName": "Pollywog Charm",
    "cost": null
  },
  "1607": {
    "shortName": "item_magnifying_monocle",
    "longName": "Magnifying Monocle",
    "cost": null
  },
  "1608": {
    "shortName": "item_pyrrhic_cloak",
    "longName": "Pyrrhic Cloak",
    "cost": null
  },
  "1609": {
    "shortName": "item_madstone_bundle",
    "longName": "Madstone Bundle",
    "cost": null
  },
  "1610": {
    "shortName": "item_miniboss_minion_summoner",
    "longName": "",
    "cost": null
  },
  "1636": {
    "shortName": "item_crystal_raindrop",
    "longName": "Crystal Raindrop",
    "cost": null
  },
  "1637": {
    "shortName": "item_kobold_cup",
    "longName": "Kobold Cup",
    "cost": null
  },
  "1638": {
    "shortName": "item_dormant_curio",
    "longName": "Dormant Curio",
    "cost": null
  },
  "1639": {
    "shortName": "item_sisters_shroud",
    "longName": "Sister's Shroud",
    "cost": null
  },
  "1640": {
    "shortName": "item_jidi_pollen_bag",
    "longName": "Jidi Pollen Bag",
    "cost": null
  },
  "1641": {
    "shortName": "item_outworld_staff",
    "longName": "Outworld Staff",
    "cost": null
  },
  "1642": {
    "shortName": "item_dezun_bloodrite",
    "longName": "Dezun Bloodrite",
    "cost": null
  },
  "1643": {
    "shortName": "item_giant_maul",
    "longName": "Giant's Maul",
    "cost": null
  },
  "1644": {
    "shortName": "item_divine_regalia",
    "longName": "Divine Regalia",
    "cost": null
  },
  "1645": {
    "shortName": "item_divine_regalia_broken",
    "longName": "Disgraced Regalia",
    "cost": null
  },
  "1646": {
    "shortName": "item_circlet_of_the_flayed_twins",
    "longName": "Circlet of the Flayed Twins",
    "cost": null
  },
  "1647": {
    "shortName": "item_enhancement_fierce",
    "longName": "Fierce",
    "cost": null
  },
  "1648": {
    "shortName": "item_enhancement_dominant",
    "longName": "Dominant",
    "cost": null
  },
  "1649": {
    "shortName": "item_enhancement_restorative",
    "longName": "Restorative",
    "cost": null
  },
  "1650": {
    "shortName": "item_enhancement_thick",
    "longName": "Thick",
    "cost": null
  },
  "1651": {
    "shortName": "item_enhancement_curious",
    "longName": "Unleashed",
    "cost": null
  },
  "1652": {
    "shortName": "item_furion_gold_bag",
    "longName": "Bag of Gold",
    "cost": null
  },
  "1715": {
    "shortName": "item_recipe_specialists_array",
    "longName": "",
    "cost": null
  },
  "1716": {
    "shortName": "item_weighted_dice",
    "longName": "Weighted Dice",
    "cost": null
  },
  "1717": {
    "shortName": "item_ash_legion_shield",
    "longName": "Ash Legion Shield",
    "cost": null
  },
  "1718": {
    "shortName": "item_riftshadow_prism",
    "longName": "Riftshadow Prism",
    "cost": null
  },
  "1719": {
    "shortName": "item_metamorphic_mandible",
    "longName": "Metamorphic Mandible",
    "cost": null
  },
  "1720": {
    "shortName": "item_idol_of_screeauk",
    "longName": "Idol of Scree'Auk",
    "cost": null
  },
  "1721": {
    "shortName": "item_flayers_bota",
    "longName": "Flayer's Bota",
    "cost": null
  },
  "1801": {
    "shortName": "item_caster_rapier",
    "longName": "",
    "cost": null
  },
  "1802": {
    "shortName": "item_tiara_of_selemene",
    "longName": "Tiara of Selemene",
    "cost": null
  },
  "1803": {
    "shortName": "item_doubloon",
    "longName": "Doubloon",
    "cost": null
  },
  "1804": {
    "shortName": "item_roshans_banner",
    "longName": "Roshan's Banner",
    "cost": null
  },
  "1805": {
    "shortName": "item_recipe_devastator",
    "longName": "Parasma Recipe",
    "cost": null
  },
  "1806": {
    "shortName": "item_devastator",
    "longName": "Parasma",
    "cost": null
  },
  "1807": {
    "shortName": "item_recipe_angels_demise",
    "longName": "Khanda Recipe",
    "cost": null
  },
  "1808": {
    "shortName": "item_angels_demise",
    "longName": "Khanda",
    "cost": null
  },
  "2091": {
    "shortName": "item_tier1_token",
    "longName": "Tier 1 Token",
    "cost": null
  },
  "2092": {
    "shortName": "item_tier2_token",
    "longName": "Tier 2 Token",
    "cost": null
  },
  "2093": {
    "shortName": "item_tier3_token",
    "longName": "Tier 3 Token",
    "cost": null
  },
  "2094": {
    "shortName": "item_tier4_token",
    "longName": "Tier 4 Token",
    "cost": null
  },
  "2095": {
    "shortName": "item_tier5_token",
    "longName": "Tier 5 Token",
    "cost": null
  },
  "2096": {
    "shortName": "item_vindicators_axe",
    "longName": "Vindicator's Axe",
    "cost": null
  },
  "2097": {
    "shortName": "item_duelist_gloves",
    "longName": "Duelist Gloves",
    "cost": null
  },
  "2098": {
    "shortName": "item_horizons_equilibrium",
    "longName": "",
    "cost": null
  },
  "2099": {
    "shortName": "item_blighted_spirit",
    "longName": "",
    "cost": null
  },
  "2190": {
    "shortName": "item_dandelion_amulet",
    "longName": "Dandelion Amulet",
    "cost": null
  },
  "2191": {
    "shortName": "item_turtle_shell",
    "longName": "",
    "cost": null
  },
  "2192": {
    "shortName": "item_martyrs_plate",
    "longName": "Martyr's Plate",
    "cost": null
  },
  "2193": {
    "shortName": "item_gossamer_cape",
    "longName": "Gossamer Cape",
    "cost": null
  },
  "4204": {
    "shortName": "item_famango",
    "longName": "Healing Lotus",
    "cost": null
  },
  "4205": {
    "shortName": "item_great_famango",
    "longName": "Great Healing Lotus",
    "cost": null
  },
  "4206": {
    "shortName": "item_greater_famango",
    "longName": "Greater Healing Lotus",
    "cost": null
  },
  "4207": {
    "shortName": "item_recipe_great_famango",
    "longName": "",
    "cost": null
  },
  "4208": {
    "shortName": "item_recipe_greater_famango",
    "longName": "",
    "cost": null
  },
  "4300": {
    "shortName": "item_ofrenda",
    "longName": "Beloved Memory",
    "cost": null
  },
  "4301": {
    "shortName": "item_ofrenda_shovel",
    "longName": "Scrying Shovel",
    "cost": null
  },
  "4302": {
    "shortName": "item_ofrenda_pledge",
    "longName": "Forebearer's Fortune",
    "cost": null
  }
}
