// Auto-generated by scripts/update-static-data.cjs
// Last updated: 2026-03-30T08:37:39.769Z

export interface PatchData {
  name: string
  lowerBound: number
  upperBound: number
}

/** All patches, newest first */
export const patches: PatchData[] = [
  {
    "name": "7.41",
    "lowerBound": 8742591748,
    "upperBound": 9999999999
  },
  {
    "name": "7.40",
    "lowerBound": 8607264409,
    "upperBound": 8742591747
  },
  {
    "name": "7.39",
    "lowerBound": 8303635292,
    "upperBound": 8607264408
  },
  {
    "name": "7.38",
    "lowerBound": 8181154673,
    "upperBound": 8303635291
  },
  {
    "name": "7.37",
    "lowerBound": 7873633785,
    "upperBound": 8181154672
  },
  {
    "name": "7.36",
    "lowerBound": 7750648554,
    "upperBound": 7873633784
  },
  {
    "name": "7.35",
    "lowerBound": 7488336583,
    "upperBound": 7750648553
  },
  {
    "name": "7.34",
    "lowerBound": 7276533753,
    "upperBound": 7488336582
  },
  {
    "name": "7.33",
    "lowerBound": 7116365945,
    "upperBound": 7276533752
  },
  {
    "name": "7.32",
    "lowerBound": 6721431596,
    "upperBound": 7116365944
  },
  {
    "name": "7.31",
    "lowerBound": 6446925928,
    "upperBound": 6721431595
  },
  {
    "name": "7.30",
    "lowerBound": 6140264285,
    "upperBound": 6446925927
  },
  {
    "name": "7.29",
    "lowerBound": 5936309157,
    "upperBound": 6140264284
  },
  {
    "name": "7.28",
    "lowerBound": 5746362067,
    "upperBound": 5936309156
  },
  {
    "name": "7.27",
    "lowerBound": 5490967400,
    "upperBound": 5746362066
  },
  {
    "name": "7.26",
    "lowerBound": 5362184213,
    "upperBound": 5490967399
  },
  {
    "name": "7.25",
    "lowerBound": 5292577303,
    "upperBound": 5362184212
  },
  {
    "name": "7.24",
    "lowerBound": 5212816886,
    "upperBound": 5292577302
  },
  {
    "name": "7.23",
    "lowerBound": 5129195863,
    "upperBound": 5212816885
  },
  {
    "name": "7.22",
    "lowerBound": 4780985993,
    "upperBound": 5129195862
  },
  {
    "name": "7.21",
    "lowerBound": 4373269191,
    "upperBound": 4780985992
  },
  {
    "name": "7.20",
    "lowerBound": 4226773444,
    "upperBound": 4373269190
  },
  {
    "name": "7.19",
    "lowerBound": 4031939644,
    "upperBound": 4226773443
  },
  {
    "name": "7.18",
    "lowerBound": 3973246065,
    "upperBound": 4031939643
  },
  {
    "name": "7.17",
    "lowerBound": 3943981462,
    "upperBound": 3973246064
  },
  {
    "name": "7.16",
    "lowerBound": 3917861324,
    "upperBound": 3943981461
  },
  {
    "name": "7.15",
    "lowerBound": 3879484576,
    "upperBound": 3917861323
  },
  {
    "name": "7.14",
    "lowerBound": 3851831476,
    "upperBound": 3879484575
  },
  {
    "name": "7.13",
    "lowerBound": 3829635896,
    "upperBound": 3851831475
  },
  {
    "name": "7.12",
    "lowerBound": 3805793827,
    "upperBound": 3829635895
  },
  {
    "name": "7.11",
    "lowerBound": 3782286728,
    "upperBound": 3805793826
  },
  {
    "name": "7.10",
    "lowerBound": 3759179135,
    "upperBound": 3782286727
  },
  {
    "name": "7.09",
    "lowerBound": 3736025441,
    "upperBound": 3759179134
  },
  {
    "name": "7.08",
    "lowerBound": 3711789206,
    "upperBound": 3736025440
  },
  {
    "name": "7.07",
    "lowerBound": 3534217746,
    "upperBound": 3711789205
  },
  {
    "name": "7.06",
    "lowerBound": 3181288356,
    "upperBound": 3534217745
  },
  {
    "name": "7.05",
    "lowerBound": 3108980749,
    "upperBound": 3181288355
  },
  {
    "name": "7.04",
    "lowerBound": 3073249065,
    "upperBound": 3108980748
  },
  {
    "name": "7.03",
    "lowerBound": 3057557407,
    "upperBound": 3073249064
  },
  {
    "name": "7.02",
    "lowerBound": 2985537146,
    "upperBound": 3057557406
  },
  {
    "name": "7.01",
    "lowerBound": 2861216742,
    "upperBound": 2985537145
  },
  {
    "name": "7.00",
    "lowerBound": 2842077011,
    "upperBound": 2861216741
  },
  {
    "name": "6.88",
    "lowerBound": 2430984807,
    "upperBound": 2842077010
  },
  {
    "name": "6.87",
    "lowerBound": 2317015334,
    "upperBound": 2430984806
  },
  {
    "name": "6.86",
    "lowerBound": 2007521780,
    "upperBound": 2317015333
  },
  {
    "name": "6.85",
    "lowerBound": 1818925460,
    "upperBound": 2007521779
  },
  {
    "name": "6.84",
    "lowerBound": 1435327813,
    "upperBound": 1818925459
  },
  {
    "name": "6.83",
    "lowerBound": 1097824358,
    "upperBound": 1435327812
  },
  {
    "name": "6.82",
    "lowerBound": 920489421,
    "upperBound": 1097824357
  },
  {
    "name": "6.81",
    "lowerBound": 634455782,
    "upperBound": 920489420
  },
  {
    "name": "6.80",
    "lowerBound": 490145179,
    "upperBound": 634455781
  },
  {
    "name": "6.79",
    "lowerBound": 353805307,
    "upperBound": 490145178
  },
  {
    "name": "6.78",
    "lowerBound": 211765789,
    "upperBound": 353805306
  },
  {
    "name": "6.77",
    "lowerBound": 81640063,
    "upperBound": 211765788
  },
  {
    "name": "6.76",
    "lowerBound": 53113899,
    "upperBound": 81640062
  },
  {
    "name": "6.75",
    "lowerBound": 46254734,
    "upperBound": 53113898
  },
  {
    "name": "6.74",
    "lowerBound": -100,
    "upperBound": 46254733
  }
]

/** All patch names, newest first */
export const patchNames: string[] = patches.map(p => p.name)

/** Get patch by name */
export function getPatchByName(name: string): PatchData | undefined {
  return patches.find(p => p.name === name)
}

/** Total number of patches */
export const PATCH_COUNT = 57
